[profile.default]
optimizer_runs = 800
via_ir = false
ffi = true
fs_permissions = [
    { access = "read-write", path = ".forge-snapshots/" },
    { access = "read", path = "./out" },
]
cancun = true
src = "src"
out = "out"
libs = ["lib"]

[profile.default.fuzz]
runs = 100
seed = "0x4444"

[fmt]
bracket_spacing = true
int_types = "long"
line_length = 90
multiline_func_header = "all"
number_underscore = "thousands"
quote_style = "double"
tab_width = 4
wrap_comments = true

[profile.ci.fuzz]
runs = 1000

[profile.ci]
fuzz_runs = 100000
solc = "./bin/solc-static-linux"

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
